import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { SnapshotGenerator } from "../src/generator";

describe("SnapshotGenerator", () => {
	describe("generateHeader", () => {
		beforeEach(() => {
			vi.useFakeTimers();
			const date = new Date(2026, 0, 31, 12, 0, 0);
			vi.setSystemTime(date);
		});

		afterEach(() => {
			vi.useRealTimers();
		});

		it("should generate a header with the folder name and current date", () => {
			const folder = "My Notes";
			const result = (SnapshotGenerator as any).generateHeader(folder);
			expect(result).toContain("# Vault Snapshot: My Notes");
			expect(result).toContain("Generated on");
			expect(result).toContain(new Date().toLocaleString());
		});
	});

	describe("generateBody", () => {
		it("should return a placeholder message if the file list is empty", () => {
			const result = (SnapshotGenerator as any).generateBody([]);
			expect(result).toBe("_No notes found in this folder._");
		});

		it("should format a list of files with tags and links", () => {
			const files = [
				{
					title: "Note 1",
					tags: ["#tag1", "#tag2"],
					links: ["Link 1", "Link 2"],
				},
				{
					title: "Note 2",
					tags: [],
					links: ["Link 3"],
				},
			];
			const result = (SnapshotGenerator as any).generateBody(files);
			expect(result).toContain("- **Note 1** #tag1 #tag2 -> [[Link 1]], [[Link 2]]");
			expect(result).toContain("- **Note 2** -> [[Link 3]]");
		});

		it("should format files without tags or links correctly", () => {
			const files = [
				{
					title: "Note 1",
					tags: [],
					links: [],
				},
			];
			const result = (SnapshotGenerator as any).generateBody(files);
			expect(result).toBe("- **Note 1**");
		});
	});

	describe("generateFooter", () => {
		it("should generate a footer with the plugin name", () => {
			const result = (SnapshotGenerator as any).generateFooter();
			expect(result).toContain("---");
			expect(result).toContain("_Generated by Vault Snapshot_");
		});
	});
});
