import { FileMetadata } from "./extractor";

export class SnapshotGenerator {
	static generate(files: FileMetadata[], targetFolder: string): string {
		const header = this.generateHeader(targetFolder);
		const body = this.generateBody(files);
		const footer = this.generateFooter();

		return `${header}\n\n${body}\n\n${footer}`;
	}

	private static generateHeader(targetFolder: string): string {
		return `# Vault Snapshot: ${targetFolder}\n\nGenerated on ${new Date().toLocaleString()}`;
	}

	private static generateBody(files: FileMetadata[]): string {
		if (files.length === 0) {
			return "_No notes found in this folder._";
		}

		return files
			.map((file) => {
				const tags =
					file.tags.length > 0 ? ` ${file.tags.join(" ")}` : "";
				const links =
					file.links.length > 0
						? ` -> ${file.links.map((l) => `[[${l}]]`).join(", ")}`
						: "";
				return `- **${file.title}**${tags}${links}`;
			})
			.join("\n");
	}

	private static generateFooter(): string {
		return `---\n_Generated by Vault Snapshot_`;
	}
}
